# Name: Amina Khan  
# Roll: PIAIC57987
# Assignment 1 Batch 19 Quarter 2

In [1]:
# Importing numpy library as rusel
import numpy as rusel

In [2]:
#method 1
rusel.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
#method 2
rusel.add(8,2)

10

In [4]:
#method 3
rusel.subtract(15,7)

8

In [5]:
#method 4
rusel.multiply(4,2)

8

In [6]:
#method 5
rusel.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
#method 6
rusel.ones(1)

array([1.])

In [8]:
#method 7
rusel.ones((5,4),dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
#method 8
rusel.full((5,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [10]:
#method 9
rusel.arange(5,30,4)

array([ 5,  9, 13, 17, 21, 25, 29])

In [11]:
#method 10
rusel.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [12]:
#method 11
rusel.random.random((3,2))

array([[0.50708646, 0.07881806],
       [0.51296666, 0.62613309],
       [0.63376871, 0.2055943 ]])

In [13]:
#method 12
x=rusel.empty(7)
x

array([4.64532021e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 2.44048419e-152])

In [14]:
#method 13
y=rusel.empty(2)
y

array([4.64532021e-310, 2.44048419e-152])

In [16]:
#method 14
rint=rusel.random.randint(0,20,(5,5))
rint

array([[11, 16, 12, 14, 16],
       [ 9,  4,  3,  0, 14],
       [16, 12,  3,  8, 16],
       [10, 19, 14, 17, 14],
       [ 5,  7,  7, 19,  5]])

In [17]:
#method 15
rusel.shape(x)

(7,)

In [18]:
#method 16
rusel.size(x)

7

In [19]:
#method 17
print(x.dtype)
print(y.dtype)
print(rint.dtype)

float64
float64
int64


In [20]:
#method 18
print(x.data)
print(y.data)
print(rint.data)

In [21]:
#method 19
print(x.itemsize)
print(y.itemsize)
print(rint.itemsize)

8
8
8


In [22]:
#method 20
print(x.ndim)
print(y.ndim)
print(rint.ndim)

1
1
2


In [23]:
#method 21
rusel.random.default_rng(1)

Generator(PCG64) at 0x7F19417CF6D8

In [24]:
#method 22
new=rusel.random.randint(11,20,(5,5))
new

array([[11, 16, 12, 14, 16],
       [15, 17, 17, 15, 18],
       [16, 14, 14, 18, 19],
       [18, 19, 12, 14, 18],
       [18, 17, 17, 11, 19]])

In [25]:
#method 23
new.min()

11

In [26]:
#method 24
new.max()

19

In [27]:
#method 25
new.mean()

15.8

In [28]:
#method 26
new.sum()

395

In [29]:
#method 27
rusel.exp(new)

array([[5.98741417e+04, 8.88611052e+06, 1.62754791e+05, 1.20260428e+06,
        8.88611052e+06],
       [3.26901737e+06, 2.41549528e+07, 2.41549528e+07, 3.26901737e+06,
        6.56599691e+07],
       [8.88611052e+06, 1.20260428e+06, 1.20260428e+06, 6.56599691e+07,
        1.78482301e+08],
       [6.56599691e+07, 1.78482301e+08, 1.62754791e+05, 1.20260428e+06,
        6.56599691e+07],
       [6.56599691e+07, 2.41549528e+07, 2.41549528e+07, 5.98741417e+04,
        1.78482301e+08]])

In [30]:
#method 28
rusel.random.seed(0)
rusel.random.random((2,5))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152]])

In [31]:
#method 29
new.ravel()

array([11, 16, 12, 14, 16, 15, 17, 17, 15, 18, 16, 14, 14, 18, 19, 18, 19,
       12, 14, 18, 18, 17, 17, 11, 19])

In [32]:
#method 30
rusel.abs(new)

array([[11, 16, 12, 14, 16],
       [15, 17, 17, 15, 18],
       [16, 14, 14, 18, 19],
       [18, 19, 12, 14, 18],
       [18, 17, 17, 11, 19]])

In [35]:
#method 31
rusel.pi

3.141592653589793

In [36]:
#method 32
rusel.sin(new)

array([[-0.99999021, -0.28790332, -0.53657292,  0.99060736, -0.28790332],
       [ 0.65028784, -0.96139749, -0.96139749,  0.65028784, -0.75098725],
       [-0.28790332,  0.99060736,  0.99060736, -0.75098725,  0.14987721],
       [-0.75098725,  0.14987721, -0.53657292,  0.99060736, -0.75098725],
       [-0.75098725, -0.96139749, -0.96139749, -0.99999021,  0.14987721]])

In [37]:
#method 33
rusel.cos(new)

array([[ 0.0044257 , -0.95765948,  0.84385396,  0.13673722, -0.95765948],
       [-0.75968791, -0.27516334, -0.27516334, -0.75968791,  0.66031671],
       [-0.95765948,  0.13673722,  0.13673722,  0.66031671,  0.98870462],
       [ 0.66031671,  0.98870462,  0.84385396,  0.13673722,  0.66031671],
       [ 0.66031671, -0.27516334, -0.27516334,  0.0044257 ,  0.98870462]])

In [38]:
#method 34
rusel.tan(new)

array([[-2.25950846e+02,  3.00632242e-01, -6.35859929e-01,
         7.24460662e+00,  3.00632242e-01],
       [-8.55993401e-01,  3.49391565e+00,  3.49391565e+00,
        -8.55993401e-01, -1.13731371e+00],
       [ 3.00632242e-01,  7.24460662e+00,  7.24460662e+00,
        -1.13731371e+00,  1.51589471e-01],
       [-1.13731371e+00,  1.51589471e-01, -6.35859929e-01,
         7.24460662e+00, -1.13731371e+00],
       [-1.13731371e+00,  3.49391565e+00,  3.49391565e+00,
        -2.25950846e+02,  1.51589471e-01]])

In [41]:
#method 35
rusel.arcsin(0.8)

0.9272952180016123

In [43]:
#method 36
rusel.arccos(0.8)

0.6435011087932843

In [45]:
#method 37
rusel.arctan(0.8)

0.6747409422235527

In [46]:
#method 38
rusel.log(new)

array([[2.39789527, 2.77258872, 2.48490665, 2.63905733, 2.77258872],
       [2.7080502 , 2.83321334, 2.83321334, 2.7080502 , 2.89037176],
       [2.77258872, 2.63905733, 2.63905733, 2.89037176, 2.94443898],
       [2.89037176, 2.94443898, 2.48490665, 2.63905733, 2.89037176],
       [2.89037176, 2.83321334, 2.83321334, 2.39789527, 2.94443898]])

In [48]:
#method 39
rusel.log2(new)

array([[3.45943162, 4.        , 3.5849625 , 3.80735492, 4.        ],
       [3.9068906 , 4.08746284, 4.08746284, 3.9068906 , 4.169925  ],
       [4.        , 3.80735492, 3.80735492, 4.169925  , 4.24792751],
       [4.169925  , 4.24792751, 3.5849625 , 3.80735492, 4.169925  ],
       [4.169925  , 4.08746284, 4.08746284, 3.45943162, 4.24792751]])

In [49]:
#method 40
rusel.log10(new)

array([[1.04139269, 1.20411998, 1.07918125, 1.14612804, 1.20411998],
       [1.17609126, 1.23044892, 1.23044892, 1.17609126, 1.25527251],
       [1.20411998, 1.14612804, 1.14612804, 1.25527251, 1.2787536 ],
       [1.25527251, 1.2787536 , 1.07918125, 1.14612804, 1.25527251],
       [1.25527251, 1.23044892, 1.23044892, 1.04139269, 1.2787536 ]])

In [50]:
#method 41
rusel.add.reduce(new)

array([78, 83, 72, 72, 90])

In [51]:
#method 42
rusel.multiply.reduce(new)

array([ 855360, 1229984,  582624,  582120, 1871424])

In [52]:
#method 43
rusel.add.accumulate(new)

array([[11, 16, 12, 14, 16],
       [26, 33, 29, 29, 34],
       [42, 47, 43, 47, 53],
       [60, 66, 55, 61, 71],
       [78, 83, 72, 72, 90]])

In [53]:
#method 44
rusel.multiply.accumulate(new)

array([[     11,      16,      12,      14,      16],
       [    165,     272,     204,     210,     288],
       [   2640,    3808,    2856,    3780,    5472],
       [  47520,   72352,   34272,   52920,   98496],
       [ 855360, 1229984,  582624,  582120, 1871424]])

In [54]:
#method 45
rusel.power(2,3)

8

In [59]:
#method 46
rusel.hsplit(new,5)

[array([[11],
        [15],
        [16],
        [18],
        [18]]),
 array([[16],
        [17],
        [14],
        [19],
        [17]]),
 array([[12],
        [17],
        [14],
        [12],
        [17]]),
 array([[14],
        [15],
        [18],
        [14],
        [11]]),
 array([[16],
        [18],
        [19],
        [18],
        [19]])]

In [63]:
#method 47
rusel.vsplit(new,5)

[array([[11, 16, 12, 14, 16]]),
 array([[15, 17, 17, 15, 18]]),
 array([[16, 14, 14, 18, 19]]),
 array([[18, 19, 12, 14, 18]]),
 array([[18, 17, 17, 11, 19]])]

In [64]:
#method 48
rusel.absolute(new)

array([[11, 16, 12, 14, 16],
       [15, 17, 17, 15, 18],
       [16, 14, 14, 18, 19],
       [18, 19, 12, 14, 18],
       [18, 17, 17, 11, 19]])

In [65]:
#method 49
rusel.prod(new)

-7338539208853684224

In [66]:
#method 50
rusel.std(new)

2.449489742783178

In [67]:
#method 51
rusel.var(new)

6.0